version: "3"

services:
    php:
        build: ./php
        volumes:
            - ./php:/var/www/html
        ports:
            - 8010:80
        container_name: php_csrf
    php1:
        build: ./php_attack
        volumes:
            - ./php_attack:/var/www/html
        ports:
            - 8011:80
        container_name: php_csrf_attack
    mysql:
        image: mysql:8.0
        volumes:
            - ./mysql/start:/docker-entrypoint-initdb.d
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=php1
            - MYSQL_PASSWORD=pjk-3kjf-Abc
        container_name: mysql_csrf
